---
title: "Client Report - Finding Relationships in Baseball"
subtitle: "Course DS 250"
author: "Ryan Lee"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
import pandas as pd 
import numpy as np
import sqlite3
from lets_plot import *

LetsPlot.setup_html(isolated_frame=True)
```


```{python}
# Learn morea about Code Cells: https://quarto.org/docs/reference/cells/cells-jupyter.html

# Include and execute your code here
sqlite_file = 'lahmansbaseballdb.sqlite'
# this file must be in the same location as your .qmd or .py file
con = sqlite3.connect(sqlite_file)
```

## QUESTION|TASK 1

__Write an SQL query to create a new dataframe about baseball players who attended BYU-Idaho. The new table should contain five columns: playerID, schoolID, salary, and the yearID/teamID associated with each salary. Order the table by salary (highest to lowest) and print out the table in your report.__  

_I noticed that lindsma is the only one that is seen on the first 10 listings for highest salary. If we see the rest of the chart, stephga can be seen earning a salary who attended byui_

```{python}
pq = """
    SELECT 
        school.playerID, 
        school.schoolID, 
        salary.salary, 
        salary.yearID, 
        salary.teamID
    FROM collegeplaying AS school
    JOIN salaries AS salary ON school.playerID = salary.playerID
    WHERE school.schoolID = 'idbyuid'
    ORDER BY salary.salary DESC

    """
results = pd.read_sql_query(pq,con)

results
```


## QUESTION|TASK 2

__This three-part question requires you to calculate batting average (number of hits divided by the number of at-bats)__  
    a. Write an SQL query that provides playerID, yearID, and batting average for players with at least 1 at bat that year. Sort the table from highest batting average to lowest, and then by playerid alphabetically. Show the top 5 results in your report.  
    b. Use the same query as above, but only include players with at least 10 at bats that year. Print the top 5 results.  
    c. Now calculate the batting average for players over their entire careers (all years combined). Only include players with at least 100 at bats, and print the top 5 results.  

_For table 1, we see the top 5 players averages for batting are displayed. This one is in alphabetical order._ 

_For table 2, we find the average batting that have more than 10 bats a year. We see the average batting goes down, meaning that a player from table 1 got one hit and made it, making it look like a perfect record._

_For table 3, we take the average batter's batting over their entire career, but only if they have over 100 average batting. The number even goes furthur down._

```{python}
pq1 = '''
    SELECT playerID, yearID, round(cast(H as float) / AB, 3) as average_batting
    from batting
    where AB > 0
    order by average_batting desc, playerID asc
    limit 5;
'''
pd.read_sql_query(pq1, con)

```

```{python}
pq2 = '''
    SELECT playerID, yearID, round(cast(H as float) / AB, 3) as average_batting
    from batting
    where AB > 9
    order by average_batting desc, playerID asc
    limit 5;
'''
pd.read_sql_query(pq2, con)

```

```{python}
pq3 = '''
    SELECT playerID, round(sum(cast(H as float)) / sum(AB), 3) as average_batting
    FROM batting
    GROUP BY playerID
    HAVING sum(AB) > 100
    ORDER BY average_batting desc, playerID asc
    LIMIT 5;
'''
pd.read_sql_query(pq3, con)

```


## QUESTION|TASK 3

__Pick any two baseball teams and compare them using a metric of your choice (average salary, home runs, number of wins, etc). Write an SQL query to get the data you need, then make a graph using Lets-Plot to visualize the comparison. What do you learn?__

_The two teams I wanted to compare are the Seattle Mariners and the New York Mets. (They're across the country from one another)_

_I took all info from both teams and got the sum for each Home Run. Based on the graph, we see that the Mets have been around longer than the Mariners and perform on average much better than the Mariners._

```{python}
# SEA = Seattle Mariners
# NYN = New York Mets

pq = '''
    SELECT 
        yearID, 
        sum(case when teamID = 'SEA' then HR else 0 end) as mariners_hr,
        sum(case when teamID = 'NYN' then HR else 0 end) as mets_hr
        
    FROM teams
    WHERE teamID in ('SEA', 'NYN')
    GROUP BY yearID
    HAVING 
        sum(case when teamID = 'SEA' then HR else 0 end) > 0 OR sum(case when teamID = 'NYN' then HR else 0 end) > 0
    ORDER BY yearID;
'''

chart = pd.read_sql_query(pq, con)

ggplot(chart, aes(x='yearID')) + geom_line(aes(y='mariners_hr'), color='#005C5C', size=1.2) + geom_line(aes(y='mets_hr'), color='#FF6600', size=1.2) + theme_bw() + labs(title='Mariners vs Mets: Yearly Home Runs', x='Year', y='Total Home Runs') + scale_x_continuous(format='d')

```

---

## STRETCH QUESTION|TASK 1

__Advanced Salary Distribution by Position (with Case Statement):__  

    * Write an SQL query that provides a summary table showing the average salary for each position (e.g., pitcher, catcher, outfielder). Position information can be found in the fielding table in the POS column. 
    
        Include the following columns:

        * position
        * average_salary
        * total_players
        * highest_salary  

    * The highest_salary column should display the highest salary ever earned by a player in that position. 

    * Additionally, create a new column called salary_category using a case statement:  

        * If the average salary is above $3 million, categorize it as “High Salary.”
        * If the average salary is between $2 million and $3 million, categorize it as “Medium Salary.”
        * Otherwise, categorize it as “Low Salary.”  

    * Order the table by average salary in descending order.

    **Hint:** Beware, it is common for a player to play multiple positions in a single year. For this analysis, each player’s salary should only be counted toward one position in a given year: the position at which they played the most games that year. This will likely require a (sub-query)[https://docs.data.world/documentation/sql/concepts/advanced/WITH.html].

    

_type your results and analysis here_

```{python}
# Include and execute your code here


```


## STRETCH QUESTION|TASK 2

__Advanced Career Longevity and Performance (with Subqueries):__

    * Calculate the average career length (in years) for players who have played at least **10 games**. Then, identify the top 10 players with the longest careers (based on the number of years they played). Include their: 

        * playerID
        * first_name
        * last_name
        * career_length

    * The career_length should be calculated as the difference between the maximum and minimum yearID for each player.  

_This one was really tough. By gathering all the data needed, from the Player ID, then we call their first and last name. Then we organized the players Career Length by making sure they at least have 10 games played. We then display from most to least the career lengths and see that Altrock, O'Rourke and Minoso are the top 3 to have the longest careers in baseball._

```{python}
sq2 = '''
with player_games as (
    select playerID, yearID, sum(G_all) as total_games
    from appearances
    group by playerID, yearID
),
player_qualified as (
    select playerID
    from player_games
    group by playerID
    having sum(total_games) >= 10
),
length_career as (
    select 
        qp.playerID,
        min(gpy.yearID) as first_year,
        max(gpy.yearID) as last_year,
        max(gpy.yearID) - min(gpy.yearID) as career_length
    from player_qualified qp
    join player_games gpy on qp.playerID = gpy.playerID
    group by qp.playerID
),
top_10_longest_careers as (
    select *
    from length_career
    order by career_length desc
    limit 10
)
select 
    c.playerID,
    p.nameFirst as first_name,
    p.nameLast as last_name,
    c.career_length
from top_10_longest_careers c
join people p on c.playerID = p.playerID
order by c.career_length desc;
'''
pd.read_sql_query(sq2, con)
```

---