---
title: "Client Report - Late Flights & Missing Data (JSON)"
subtitle: "Course DS 250"
author: "Ryan Lee"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
import pandas as pd
import numpy as np
from lets_plot import *

LetsPlot.setup_html(isolated_frame=True)
```


```{python}
# Learn morea about Code Cells: https://quarto.org/docs/reference/cells/cells-jupyter.html

# Include and execute your code here
df = pd.read_json("https://github.com/byuidatascience/data4missing/raw/master/data-raw/flights_missing/flights_missing.json")
```

## Elevator pitch
_A SHORT (2-3 SENTENCES) PARAGRAPH THAT `DESCRIBES KEY INSIGHTS` TAKEN FROM METRICS IN THE PROJECT RESULTS THINK TOP OR MOST IMPORTANT RESULTS._ (Note: this is not a summary of the project, but a summary of the results.)

_A Client has requested this analysis and this is your one shot of what you would say to your boss in a 2 min elevator ride before he takes your report and hands it to the client._

_If you ever had question or concerns about taking an airplane anywhere, I have found that taking any plane from the East Coast have the longest delays. And November is suprisingly the best month to go traveling!_

## QUESTION|TASK 1

__Fix all of the varied missing data types in the data to be consistent (all missing values should be displayed as “NaN”).__ In your report include one record example (one row) from your new data, in the raw JSON format. Your example should display the "NaN" for at least one missing value.__  

_Here, I found all data that contained a negative or null input, and replaced them all with N/A. Then just found a row with the N/A and turned it into a long string._

```{python}
replaced_df = df.replace(-999, np.nan).fillna("NaN")
json = replaced_df.iloc[2].to_json()
json

# check = replaced_df.isna().sum()
# check
```


## QUESTION|TASK 2

__Which airport has the worst delays?__ Describe the metric you chose, and why you chose it to determine the “worst” airport. Your answer should include a summary table that lists (for each airport) the total number of flights, total number of delayed flights, proportion of delayed flights, and average delay time in hours.   

_By ordering the sum of all minutes waited at each airport, You can see that Orlando Airport has the longest wait times._

```{python}
worst = df.groupby("airport_code").agg(
          Total_Flights = ("num_of_flights_total", "sum"),
          Total_Delayed_Flight = ("num_of_delays_nas", "sum"),
          Total_Hours_Delayed = ("minutes_delayed_late_aircraft", "sum")
)
sortedWorst = worst.sort_values(by="Total_Hours_Delayed", ascending=False).reset_index()
sortedWorst["Proportion_Delayed"] = (sortedWorst["Total_Flights"] / sortedWorst["Total_Delayed_Flight"]).round(2)
sortedWorst["Hours Waited"] = (sortedWorst["Total_Hours_Delayed"] / 60).round(2)
sortedWorst = sortedWorst[["airport_code", "Total_Flights", "Total_Delayed_Flight", "Proportion_Delayed", "Hours Waited"]]
sortedWorst.columns = ["Airport", "Total Flights", "Total Delayed", "Proportion Flights", "Hours Waited"]
sortedWorst
# [["airport_code", "minutes_delayed_late_aircraft"]].head()
```



## QUESTION|TASK 3

__What is the best month to fly if you want to avoid delays of any length?__ Describe the metric you chose and why you chose it to calculate your answer. Include one chart to help support your answer, with the x-axis ordered by month. (To answer this question, you will need to remove any rows that are missing the `Month` variable.)  

_Without getting any missing values, I calculated all the Delays by month, and decending from least to greatest delay in minutes. November is the quickest month, while December, even being a month later, has the longest wait time._

```{python}
replace = df.replace(-999, np.nan).replace("n/a", np.nan).dropna(subset=["month"])
parse = replace.dropna(subset=["month"])
aveDelay = parse.groupby("month")["minutes_delayed_late_aircraft"].mean().round(2)
best = aveDelay.sort_values(ascending=True).reset_index()
best.columns = ["Month", "Delays"]
best
```



## QUESTION|TASK 4

According to the BTS website, the “Weather” category only accounts for severe weather delays. Mild weather delays are not counted in the “Weather” category, but are actually included in both the “NAS” and “Late-Arriving Aircraft” categories. __Your job is to create a new column that calculates the total number of flights delayed by weather (both severe and mild).__ You will need to replace all the missing values in the Late Aircraft variable with the mean. Show your work by printing the first 5 rows of data in a table. Use these three rules for your calculations:  

    a. 100% of delayed flights in the Weather category are due to weather  
    a. 30% of all delayed flights in the Late-Arriving category are due to weather  
    a. From April to August, 40% of delayed flights in the NAS category are due to weather. The rest of the months, the proportion rises to 65%    

_By seeing the first five from the table isn't much to go off of, but what we can see is that three out of five flights are delayed by severe weather. Now just because it's January, doesn't mean that it's snow that's causing a problem. It could be a variety of different weather conditions._

```{python}
delay_mean = df.replace(-999, np.nan).fillna(df["num_of_delays_late_aircraft"].mean())
filtered_df = delay_mean[delay_mean["month"] != "n/a"].copy()
filtered_df
```


```{python}
filtered_df["flight_weather_delays"] = filtered_df["num_of_delays_weather"]
filtered_df["delayed_flights"] = filtered_df["num_of_delays_late_aircraft"] * 0.3
filtered_df
```


```{python}
fourtyMonth = ['April', 'May', 'June', 'July', 'August']
# sixtyMonth = ['September', 'October', 'November', 'December', 'January', 'February', 'March']

filtered_df.loc[:, "weather_delays"] = filtered_df.apply(
                    lambda row: row["num_of_delays_nas"] * 0.4 if row["month"] in fourtyMonth 
                           else row["num_of_delays_nas"] * 0.65, axis=1)

filtered_df["total_weather_delays"] = (filtered_df["num_of_delays_weather"] + filtered_df["weather_delays"] + filtered_df["delayed_flights"])
filtered_df["delayed_flights"] = filtered_df["delayed_flights"].round(2)
filtered_df["weather_delays"] = filtered_df["weather_delays"].round(2)
filtered_df["total_weather_delays"] = filtered_df["total_weather_delays"].round(2)
filtered_df[["month", "delayed_flights", "weather_delays", "flight_weather_delays", "total_weather_delays"]].head()
```



## QUESTION|TASK 5

__Using the new weather variable calculated above, create a barplot showing the proportion of all flights that are delayed by weather at each airport. Describe what you learn from this graph.__  

_We can see that Orlando and Atlanta have the highest weather delays, being on the East Coast and having those Hurricane storms. All of the other Airports seem to not be effected as much by weather delays._
```{python}
graphing = filtered_df.groupby('airport_code')['weather_delays'].sum().reset_index()

bars = (ggplot(graphing) +
                geom_bar(aes(x='airport_code', y='weather_delays', fill='airport_code'), stat='identity', show_legend=False) + scale_fill_discrete()
)

bars
```


---


## STRETCH QUESTION|TASK 1

__Which delay is the worst delay?__ Create a similar analysis as above for Weahter Delay with: Carrier Delay and Security Delay. Compare the proportion of delay for each of the three categories in a Chart and a Table. Describe your results.

_type your results and analysis here_

```{python}
# :)
```

---

